### ISSUE TITLE
Support monorepos

### ISSUE THREAD

**Issue by lpatino10** [listendev/action#33]
### Describe the feature or problem you’d like to solve

Hi team! My company is trying out the GitHub action right now and I've added it to one of our repos. So far so good, besides one thing I'm noticing which would be helpful for this particular repo.

This repo I'm adding it to is a monorepo, and when I try running the action at the root directory, it'll just look at the subset of packages defined in that top-level `package.json`. I tried solving that by just running the action multiple times in different working directories, which did scan everything, but then the PR comment that's generated gets overwritten for each one. Hopefully this representative example of my action makes it clearer:

```yaml
steps:
  - name: Check out repo
    uses: actions/checkout@v3

  - name: Run listen.dev on top-level packages
    uses: listendev/action@v0.2.0

  # Creates a new PR comment, overwriting the first one
  - name: Run listen.dev on subproject 1
    uses: listendev/action@v0.2.0
    with:
      workdir: apps/sub1

  # Creates a new PR comment, overwriting the second one
  - name: Run listen.dev on subproject 2
    uses: listendev/action@v0.2.0
    with:
      workdir: apps/sub2
```

### Proposed solution

The ideal solution IMO would be being able to run the action at the root and have it intelligently parse the subproject `package.json`s, putting the full report into one comment.

Alternatively, as an easier solution, maybe an option could be added so that each run of the action could be commented separately, but still be updated on new PR pushes? An action I use elsewhere in the project for commenting on PRs has something like that called a `comment_tag`: https://github.com/thollander/actions-comment-pull-request#update-a-comment
