### ISSUE TITLE
Support `ci: only` input for action

### ISSUE THREAD

**Issue by leodido** [listendev/action#65]
### Describe the feature or problem you’d like to solve

I want the action to run even when the repo doesn't contain a `package-lock.json` or a `poetry.lock`.

### Proposed solution

Make the `only` value valid for the `ci` input.

End result:

```yaml
steps:
  - uses: listendev/action@v0.9
    with:
      ci: only
      jwt: ${{ secrets.MY_LISTENDEV_JWT }}
```

### Additional context

NONE
