### ISSUE TITLE
Error: couldn't install and enable argus: exit status 1

### ISSUE THREAD

**Issue by zohairhadi** [listendev/action#71]
### Describe the bug
After creating the workflow and running listen on a PR after a commit, I'm getting the following error
`Error: couldn't install and enable argus: exit status 1`

This is my workflow file
```
name: Lstn Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: listendev/action@v0.10
          with:
            token: "..."
            jwt: ${{ secrets.LSTN_API_KEY }}
            ci: "only"
            # reporter: "gh-pull-comment"
```

### Expected vs actual behavior
Expected for listen to start generating a report of the packages, but I'm getting the following error
`Error: couldn't install and enable argus: exit status 1`

### Logs

`Error: couldn't install and enable argus: exit status 1`
